### ISSUE TITLE
需求：增加redhat/centos.yml

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-odoo#2]

**Comment by qiaofeng1227** [comment]
```shell
sudo yum install python3 python3-devel git gcc redhat-rpm-config libxslt-devel bzip2-devel openldap-devel libjpeg-devel freetype-devel -y

git clone https://github.com/odoo/odoo.git --depth 1 --branch 14.0 /opt/odoo14

cd /opt/odoo14/


pip3 install -r requirements.txt 

python3 setup.py install --prefix=/usr --root=$RPM_BUILD_ROOT --record=INSTALLED_FILES --install-lib usr/lib/python3.7/site-packages/

python3 odoo-bin --addons-path=addons -d odoo1 #指定数据库

odoo服务启动了，数据库没有配置
```
After install `pip3 install -r requirements.txt `, use yum install ok

**Comment by qiaofeng1227** [comment]
odoo requirements:
```
python3-babel
python3-feedparser
python3-mako
python3-qrcode
python3-xlrd
python3-passlib
python3-mock
python3-markupsafe
python3-stdnum
python3-xlwt
python3-jinja2
python3-vobject
python3-pyserial
python3-freezegun
python3-ofxparse
python3-docutils
python3-pytz
python3-polib
python3-suds
python3-reportlab
python3-pydot
python3-PyPDF2
python3-num2words
python3-gevent
```

**Comment by chendelin1982** [comment]
https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/p/python3-polib-1.0.7-10.el8.noarch.rpm
https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/p/python3-feedparser-5.2.1-17.el8.noarch.rpm
https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/p/python3-pydot-1.2.4-6.el8.noarch.rpm
https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/p/python3-xlrd-1.2.0-3.el8.noarch.rpm
https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/p/python3-passlib-1.7.2-1.el8.noarch.rpm
https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/p/python3-arrow-0.14.2-2.el8.noarch.rpm
https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/p/python3-freezegun-0.3.12-1.el8.1.noarch.rpm


http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/python3-jinja2-2.10.1-2.el8_0.noarch.rpm
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/python3-mako-1.0.6-13.el8.noarch.rpm
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/python3-pytz-2017.2-9.el8.noarch.rpm
http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/python3-pyparsing-2.1.10-7.el8.noarch.rpm
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/python3-jinja2-2.10.1-2.el8_0.noarch.rpm
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/python3-markupsafe-0.23-19.el8.x86_64.rpm
http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/python3-decorator-4.2.1-2.el8.noarch.rpm
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/python3-docutils-0.14-12.module_el8.3.0+562+e162826a.noarch.rpm
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/python3-pyusb-1.0.0-9.module_el8.3.0+482+9e103aab.noarch.rpm
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/python3-suds-0.7-0.8.94664ddd46a6.el8.noarch.rpm
http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/python3-six-1.11.0-8.el8.noarch.rpm
http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/python3-mako-1.0.6-13.el8.noarch.rpm
http://mirror.centos.org/centos/8-stream/PowerTools/x86_64/os/Packages/python3-mock-2.0.0-11.el8.noarch.rpm
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/python3-gevent-1.2.2-4.el8.x86_64.rpm
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/python3-reportlab-3.4.0-8.el8.x86_64.rpm
http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/python3-dateutil-2.6.1-6.el8.noarch.rpm
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/python3-babel-2.5.1-5.el8.noarch.rpm

**Comment by chendelin1982** [comment]
Final solution: use docker installation
