### ISSUE TITLE
Ali International Cloud  odoo14-ce Initialize err

### ISSUE THREAD

**Issue by jiaosir-cn** [Websoft9/ansible-odoo#9]
**Describe the bug**

输入初始化数据  然后create databse 之后页面 internal server err 
## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [x] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
![image](https://user-images.githubusercontent.com/76861519/114809326-88e4e400-9ddc-11eb-8f9f-ed95f0962b0c.png)


```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
not published on alibabacloud

**Comment by zengxc-1996** [comment]
tested aliyun ubuntu20.04:

![image](https://user-images.githubusercontent.com/63622990/118930772-be9b6080-b978-11eb-8389-129b88ad308f.png)

No Odoo version is exported.

Other ok

![image](https://user-images.githubusercontent.com/63622990/118930919-ee4a6880-b978-11eb-90f1-53d95ba75a91.png)

**Comment by qiaofeng1227** [comment]
Done
